apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: g6frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: g6frontend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: g6frontend
        image: raniotitonk/subproject-frontend
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Test"
---
apiVersion: v1
kind: Service
metadata:
  name: g6frontend
spec:
  selector:
    app: g6frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP